sudo: required
language: ruby

rvm:
  - 2.2

os:
  - linux

before_script:
  - gem install awesome_bot
  - sudo apt-get install -y pandoc

script:
  - make epub
  - make html
  - make release
  - awesome_bot *.markdown --allow-redirect --allow-ssl --allow-dupe

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
